package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dongocquy/restful-api-gen-go/schema"
)

// Generate runs code generation for the given config
func Generate(cfg *schema.ProjectConfig, outputDir string) error {
	// Create directories
	pkgDir := filepath.Join(outputDir, cfg.PackageName)
	for _, d := range []string{outputDir, pkgDir} {
		if err := os.MkdirAll(d, 0755); err != nil {
			return fmt.Errorf("mkdir %s: %w", d, err)
		}
	}

	// 1. Generate model.go (via template)
	if err := generateModel(cfg, pkgDir); err != nil {
		return err
	}

	// 2. Generate repository.go (Go code)
	if err := generateRepository(cfg, pkgDir); err != nil {
		return err
	}

	// 3. Generate service.go (Go code)
	if err := generateService(cfg, pkgDir); err != nil {
		return err
	}

	// 4. Generate handler.go (Go code)
	if err := generateHandler(cfg, pkgDir); err != nil {
		return err
	}

	// 5. Generate router.go (Go code)
	if err := generateRouter(cfg, pkgDir); err != nil {
		return err
	}

	// 6. Generate OpenAPI spec
	if err := GenerateOpenAPI(cfg, outputDir); err != nil {
		return err
	}

	fmt.Printf("  ✓ Generated %d Go files + openapi.yaml in %s/\n", 5, pkgDir)
	return nil
}

// GenerateFull generates code + main.go for a self-contained runnable API server
func GenerateFull(cfg *schema.ProjectConfig, outputDir, serverPort string) error {
	// 1. Generate Go code into package subdirectory
	if err := Generate(cfg, outputDir); err != nil {
		return err
	}
	pkgDir := filepath.Join(outputDir, cfg.PackageName)

	// 2. Generate go.mod at the output root (so main.go can import the package)
	rootDir := outputDir
	if err := generateGoMod(cfg.ModulePath, rootDir); err != nil {
		return err
	}

	// 3. Generate main.go at root level
	return generateMain(cfg, rootDir, pkgDir, serverPort)
}

func generateGoMod(modulePath, outputRoot string) error {
	goModPath := filepath.Join(outputRoot, "go.mod")
	if _, err := os.Stat(goModPath); err == nil {
		return nil
	}

	content := fmt.Sprintf(`module %s

go 1.22

require (
	github.com/gin-gonic/gin v1.9.1
	github.com/jmoiron/sqlx v1.3.5
	github.com/denisenkom/go-mssqldb v0.12.3
)
`, modulePath)

	return os.WriteFile(goModPath, []byte(content), 0644)
}

func generateMain(cfg *schema.ProjectConfig, rootDir, pkgDir, port string) error {
	if port == "" {
		port = "8080"
	}

	connStr := buildConnStr(cfg.Database)
	importPath := cfg.ModulePath + "/" + cfg.PackageName

	mainContent := fmt.Sprintf(`package main

import (
	"log"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/jmoiron/sqlx"
	_ "github.com/denisenkom/go-mssqldb"

	"%s"
)

func main() {
	// Database connection
	connStr := os.Getenv("DB_CONN_STR")
	if connStr == "" {
		connStr = %q
	}

	db, err := sqlx.Connect("sqlserver", connStr)
	if err != nil {
		log.Fatalf("Failed to connect to database: %%v", err)
	}
	defer db.Close()

	log.Println("Connected to SQL Server")

	// Gin router
	r := gin.Default()

	// Register all generated routes
	%s.SetupRoutes(r, db)

	// Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = %q
	}

	log.Printf("Server starting on :%%s", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %%v", err)
	}
}
`, importPath, connStr, cfg.PackageName, port)

	path := filepath.Join(rootDir, "main.go")
	if err := os.WriteFile(path, []byte(mainContent), 0644); err != nil {
		return fmt.Errorf("write main.go: %w", err)
	}
	fmt.Printf("  ✓ Generated: main.go (server on :%s)\n", port)
	return nil
}

func buildConnStr(db schema.DBConfig) string {
	if db.ConnStr != "" {
		return db.ConnStr
	}
	user := db.User
	pass := db.Password
	host := db.Host
	if host == "" {
		host = "localhost"
	}
	port := db.Port
	if port == 0 {
		port = 1433
	}
	dbName := db.Database
	return fmt.Sprintf("sqlserver://%s:%s@%s:%d?database=%s&encrypt=disable", user, pass, host, port, dbName)
}

// --- Model (template-based) ---

func generateModel(cfg *schema.ProjectConfig, pkgDir string) error {
	// Build alias lookup: table name -> struct alias
	aliasMap := make(map[string]string)
	for _, t := range cfg.Tables {
		aliasMap[t.Name] = t.Alias
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf(`// Package %s - Auto-generated models
// DO NOT EDIT - Generated by restful-api-gen-go
package %s

`, cfg.PackageName, cfg.PackageName))

	if hasTimeFields(cfg.Tables) {
		b.WriteString("import \"time\"\n\n")
	}

	for _, t := range cfg.Tables {
		// Struct definition
		b.WriteString(fmt.Sprintf(`// %s represents the %s table
type %s struct {
`, t.Alias, t.Name, t.Alias))
		for _, c := range t.Columns {
			jsonTag := c.Name
			if c.Nullable {
				jsonTag += ",omitempty"
			}
			desc := c.Description
			if desc == "" {
				desc = c.Name
			}
			b.WriteString(fmt.Sprintf("	// %s\n	%s %s `json:\"%s\" db:\"%s\"`\n",
				desc, toPascal(c.Name), c.GoType, jsonTag, c.Name))
		}
		b.WriteString("}\n\n")

		// TableName method
		b.WriteString(fmt.Sprintf(`func (%s) TableName() string { return "%s" }

`, t.Alias, t.Name))

		// Relations
		for _, r := range t.Relations {
			if r.Type == "has_many" {
				// Look up the alias for the related table
				relAlias := aliasMap[r.Table]
				if relAlias == "" {
					relAlias = toPascal(r.Table)
				}
				b.WriteString(fmt.Sprintf(`// %sRelations holds related records
type %sRelations struct {
	%s []%s `+"`"+`json:"%s,omitempty"`+"`"+`
}

`, t.Alias, t.Alias, relAlias, relAlias, r.Table))
			}
		}
	}

	return writeGoFile(pkgDir, "model.go", b.String())
}

// --- Repository (generated Go code) ---

func generateRepository(cfg *schema.ProjectConfig, pkgDir string) error {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`// Package %s - Auto-generated repository layer
// DO NOT EDIT - Generated by restful-api-gen-go
package %s

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"

	"github.com/jmoiron/sqlx"
)

`, cfg.PackageName, cfg.PackageName))

	for _, t := range cfg.Tables {
		pkName := t.PrimaryKey
		pkType := "int64"
		for _, c := range t.Columns {
			if c.IsPrimaryKey {
				pkType = c.GoType
				break
			}
		}

		b.WriteString(fmt.Sprintf(`// %sRepository handles database operations for %s
type %sRepository struct {
	db *sqlx.DB
}

func New%sRepository(db *sqlx.DB) *%sRepository {
	return &%sRepository{db: db}
}

`, t.Alias, t.Name, t.Alias, t.Alias, t.Alias, t.Alias))

		// GetAll
		b.WriteString(fmt.Sprintf(`// GetAll retrieves all %s records with pagination
func (r *%sRepository) GetAll(ctx context.Context, page, pageSize int) ([]%s, int, error) {
	var total int
	if err := r.db.QueryRowContext(ctx, "SELECT COUNT(*) FROM %s").Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("count %%s: %%w", "%s", err)
	}
	offset := (page - 1) * pageSize
	rows, err := r.db.QueryxContext(ctx, "SELECT * FROM %s ORDER BY %s OFFSET ? ROWS FETCH NEXT ? ROWS ONLY", offset, pageSize)
	if err != nil {
		return nil, 0, fmt.Errorf("select %%s: %%w", "%s", err)
	}
	defer rows.Close()

	var items []%s
	for rows.Next() {
		var item %s
		if err := rows.StructScan(&item); err != nil {
			return nil, 0, fmt.Errorf("scan %%s: %%w", "%s", err)
		}
		items = append(items, item)
	}
	if items == nil {
		items = []%s{}
	}
	return items, total, nil
}

`, t.Alias, t.Alias, t.Alias, t.Name, t.Name, t.Name, pkName, t.Name, t.Alias, t.Alias, t.Name, t.Alias))

		// GetByID
		b.WriteString(fmt.Sprintf(`// GetByID retrieves a single %s by %s
func (r *%sRepository) GetByID(ctx context.Context, id %s) (*%s, error) {
	var item %s
	if err := r.db.GetContext(ctx, &item, "SELECT * FROM %s WHERE %s = ?", id); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, fmt.Errorf("get %%s by %%s: %%w", "%s", "%s", err)
	}
	return &item, nil
}

`, t.Alias, pkName, t.Alias, pkType, t.Alias, t.Alias, t.Name, pkName, t.Name, pkName))

		// Create
		autoInc := false
		for _, c := range t.Columns {
			if c.IsAutoIncrement {
				autoInc = true
				break
			}
		}

		b.WriteString(fmt.Sprintf(`// Create inserts a new %s record
func (r *%sRepository) Create(ctx context.Context, item *%s) error {
	cols, vals, args := extractInsertFields(item)
	query := fmt.Sprintf("INSERT INTO %%s (%%s) VALUES (%%s)", "%s", cols, vals)
`, t.Alias, t.Alias, t.Alias, t.Name))

		if autoInc {
			b.WriteString(fmt.Sprintf(`	if err := r.db.QueryRowContext(ctx, query+"; SELECT CAST(SCOPE_IDENTITY() AS BIGINT)", args...).Scan(&item.%s); err != nil {
		return fmt.Errorf("insert %%s: %%w", "%s", err)
	}
	return nil
}

`, toPascal(pkName), t.Name))
		} else {
			b.WriteString(fmt.Sprintf(`	_, err := r.db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("insert %%s: %%w", "%s", err)
	}
	return nil
}

`, t.Name))
		}

		// Update
		b.WriteString(fmt.Sprintf(`// Update modifies an existing %s record
func (r *%sRepository) Update(ctx context.Context, id %s, item *%s) error {
	sets, args := extractUpdateFields(item)
	args = append(args, id)
	query := fmt.Sprintf("UPDATE %%s SET %%s WHERE %s = ?", "%s", sets)
	result, err := r.db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("update %%s: %%w", "%s", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("%%s with %s=%%v not found", "%s", id)
	}
	return nil
}

`, t.Alias, t.Alias, pkType, t.Alias, pkName, t.Name, t.Name, t.Name, pkName))

		// Delete
		b.WriteString(fmt.Sprintf(`// Delete removes a %s record
func (r *%sRepository) Delete(ctx context.Context, id %s) error {
`, t.Alias, t.Alias, pkType))

		if t.SoftDelete {
			b.WriteString(fmt.Sprintf(`	if _, err := r.db.ExecContext(ctx, "UPDATE %s SET deleted_at = GETDATE() WHERE %s = ?", id); err != nil {
		return fmt.Errorf("soft-delete %%s: %%w", "%s", err)
	}
	return nil
}

`, t.Name, pkName, t.Name))
		} else {
			b.WriteString(fmt.Sprintf(`	result, err := r.db.ExecContext(ctx, "DELETE FROM %s WHERE %s = ?", id)
	if err != nil {
		return fmt.Errorf("delete %%s: %%w", "%s", err)
	}
	rows, _ := result.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("%%s with %s=%%v not found", "%s", id)
	}
	return nil
}

`, t.Name, pkName, t.Name, pkName, t.Name))
		}
	}

	// Write helper functions
	b.WriteString(`// --- Runtime helpers (reflect-based) ---

// extractInsertFields returns column names, placeholders, and values
func extractInsertFields(item interface{}) (string, string, []interface{}) {
	v := reflect.ValueOf(item).Elem()
	t := v.Type()
	var cols, placeholders []string
	var args []interface{}
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		dbTag := field.Tag.Get("db")
		if dbTag == "" {
			continue
		}
		// Skip auto-increment PKs
		val := v.Field(i)
		// Skip zero values for auto-increment fields
		if !val.IsValid() {
			continue
		}
		cols = append(cols, dbTag)
		placeholders = append(placeholders, "?")
		args = append(args, val.Interface())
	}
	return strings.Join(cols, ", "), strings.Join(placeholders, ", "), args
}

// extractUpdateFields returns SET clause and args (skipping PK)
func extractUpdateFields(item interface{}) (string, []interface{}) {
	v := reflect.ValueOf(item).Elem()
	t := v.Type()
	var sets []string
	var args []interface{}
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		dbTag := field.Tag.Get("db")
		if dbTag == "" {
			continue
		}
		val := v.Field(i)
		if !val.IsValid() {
			continue
		}
		sets = append(sets, dbTag+" = ?")
		args = append(args, val.Interface())
	}
	return strings.Join(sets, ", "), args
}
`)

	return writeGoFile(pkgDir, "repository.go", b.String())
}

// --- Service (generated Go code) ---

func generateService(cfg *schema.ProjectConfig, pkgDir string) error {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`// Package %s - Auto-generated service layer
// DO NOT EDIT - Generated by restful-api-gen-go
package %s

import (
	"context"
	"fmt"
	"time"
)

`, cfg.PackageName, cfg.PackageName))

	for _, t := range cfg.Tables {
		pkType := "int64"
		for _, c := range t.Columns {
			if c.IsPrimaryKey {
				pkType = c.GoType
				break
			}
		}

		b.WriteString(fmt.Sprintf(`// %sService handles business logic for %s
type %sService struct {
	repo *%sRepository
}

func New%sService(repo *%sRepository) *%sService {
	return &%sService{repo: repo}
}

`, t.Alias, t.Name, t.Alias, t.Alias, t.Alias, t.Alias, t.Alias, t.Alias))

		// PaginatedResult (only once)
		if b.Len() < 500 {
			b.WriteString(`// PaginatedResult is a generic paginated response
type PaginatedResult struct {
	Data       interface{} ` + "`json:\"data\"`" + `
	Total      int         ` + "`json:\"total\"`" + `
	Page       int         ` + "`json:\"page\"`" + `
	PageSize   int         ` + "`json:\"page_size\"`" + `
	TotalPages int         ` + "`json:\"total_pages\"`" + `
}

`)
		}

		// List
		b.WriteString(fmt.Sprintf(`func (s *%sService) List(ctx context.Context, page, pageSize int) (*PaginatedResult, error) {
	if page < 1 { page = 1 }
	if pageSize < 1 || pageSize > 100 { pageSize = 20 }
	items, total, err := s.repo.GetAll(ctx, page, pageSize)
	if err != nil {
		return nil, fmt.Errorf("list %%s: %%w", "%s", err)
	}
	totalPages := total / pageSize
	if total%%pageSize > 0 { totalPages++ }
	return &PaginatedResult{Data: items, Total: total, Page: page, PageSize: pageSize, TotalPages: totalPages}, nil
}

`, t.Alias, t.Name))

		// GetByID
		b.WriteString(fmt.Sprintf(`func (s *%sService) GetByID(ctx context.Context, id %s) (*%s, error) {
	item, err := s.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get %%s: %%w", "%s", err)
	}
	if item == nil {
		return nil, fmt.Errorf("%%s not found", "%s")
	}
	return item, nil
}

`, t.Alias, pkType, t.Alias, t.Name, t.Alias))

		// Create
		b.WriteString(fmt.Sprintf(`func (s *%sService) Create(ctx context.Context, item *%s) error {
	now := time.Now()
`, t.Alias, t.Alias))
		for _, c := range t.Columns {
			if c.Name == "created_at" {
				if c.GoType == "*time.Time" {
					b.WriteString("	item.CreatedAt = &now\n")
				} else {
					b.WriteString("	item.CreatedAt = now\n")
				}
			}
			if c.Name == "updated_at" {
				if c.GoType == "*time.Time" {
					b.WriteString("	item.UpdatedAt = &now\n")
				} else {
					b.WriteString("	item.UpdatedAt = now\n")
				}
			}
		}
		b.WriteString(fmt.Sprintf(`	if err := s.repo.Create(ctx, item); err != nil {
		return fmt.Errorf("create %%s: %%w", "%s", err)
	}
	return nil
}

`, t.Name))

		// Update
		b.WriteString(fmt.Sprintf(`func (s *%sService) Update(ctx context.Context, id %s, item *%s) error {
	now := time.Now()
`, t.Alias, pkType, t.Alias))
		for _, c := range t.Columns {
			if c.Name == "updated_at" {
				if c.GoType == "*time.Time" {
					b.WriteString("	item.UpdatedAt = &now\n")
				} else {
					b.WriteString("	item.UpdatedAt = now\n")
				}
			}
		}
		b.WriteString(fmt.Sprintf(`	if err := s.repo.Update(ctx, id, item); err != nil {
		return fmt.Errorf("update %%s: %%w", "%s", err)
	}
	return nil
}

`, t.Name))

		// Delete
		b.WriteString(fmt.Sprintf(`func (s *%sService) Delete(ctx context.Context, id %s) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("delete %%s: %%w", "%s", err)
	}
	return nil
}

`, t.Alias, pkType, t.Name))

		if t.SoftDelete {
			b.WriteString(fmt.Sprintf(`func (s *%sService) Restore(ctx context.Context, id %s) error {
	if err := s.repo.Restore(ctx, id); err != nil {
		return fmt.Errorf("restore %%s: %%w", "%s", err)
	}
	return nil
}

`, t.Alias, pkType, t.Name))
		}
	}

	return writeGoFile(pkgDir, "service.go", b.String())
}

// --- Handler (generated Go code) ---

func generateHandler(cfg *schema.ProjectConfig, pkgDir string) error {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`// Package %s - Auto-generated HTTP handlers
// DO NOT EDIT - Generated by restful-api-gen-go
package %s

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
)

`, cfg.PackageName, cfg.PackageName))

	for _, t := range cfg.Tables {
		b.WriteString(fmt.Sprintf(`// %sHandler handles HTTP requests for %s
type %sHandler struct {
	service *%sService
}

func New%sHandler(service *%sService) *%sHandler {
	return &%sHandler{service: service}
}

`, t.Alias, t.Name, t.Alias, t.Alias, t.Alias, t.Alias, t.Alias, t.Alias))

		// List
		b.WriteString(fmt.Sprintf(`// List%s handles GET /api/%s/%s
func (h *%sHandler) List%s(c *gin.Context) {
	page, _ := strconv.Atoi(c.DefaultQuery("page", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "20"))
	result, err := h.service.List(c.Request.Context(), page, pageSize)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, result)
}

`, t.Alias, cfg.APIVersion, t.Name, t.Alias, t.Alias))

		// GetByID
		b.WriteString(fmt.Sprintf(`// Get%s handles GET /api/%s/%s/:id
func (h *%sHandler) Get%s(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid id"})
		return
	}
	item, err := h.service.GetByID(c.Request.Context(), id)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, item)
}

`, t.Alias, cfg.APIVersion, t.Name, t.Alias, t.Alias))

		// Create
		b.WriteString(fmt.Sprintf(`// Create%s handles POST /api/%s/%s
func (h *%sHandler) Create%s(c *gin.Context) {
	var item %s
	if err := c.ShouldBindJSON(&item); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	if err := h.service.Create(c.Request.Context(), &item); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusCreated, item)
}

`, t.Alias, cfg.APIVersion, t.Name, t.Alias, t.Alias, t.Alias))

		// Update
		b.WriteString(fmt.Sprintf(`// Update%s handles PUT /api/%s/%s/:id
func (h *%sHandler) Update%s(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid id"})
		return
	}
	var item %s
	if err := c.ShouldBindJSON(&item); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	if err := h.service.Update(c.Request.Context(), id, &item); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, item)
}

`, t.Alias, cfg.APIVersion, t.Name, t.Alias, t.Alias, t.Alias))

		// Delete
		b.WriteString(fmt.Sprintf(`// Delete%s handles DELETE /api/%s/%s/:id
func (h *%sHandler) Delete%s(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid id"})
		return
	}
	if err := h.service.Delete(c.Request.Context(), id); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.Status(http.StatusNoContent)
}

`, t.Alias, cfg.APIVersion, t.Name, t.Alias, t.Alias))
	}

	return writeGoFile(pkgDir, "handler.go", b.String())
}

// --- Router (generated Go code) ---

func generateRouter(cfg *schema.ProjectConfig, pkgDir string) error {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`// Package %s - Auto-generated router
// DO NOT EDIT - Generated by restful-api-gen-go
package %s

import (
	"github.com/gin-gonic/gin"
	"github.com/jmoiron/sqlx"
)

// SetupRoutes registers all generated API routes
func SetupRoutes(router *gin.Engine, db *sqlx.DB) {
	api := router.Group("/api/%s")
`, cfg.PackageName, cfg.PackageName, cfg.APIVersion))

	for _, t := range cfg.Tables {
		lname := firstLower(t.Alias)
		b.WriteString(fmt.Sprintf(`
	// %s routes
	%sRepo := New%sRepository(db)
	%sSvc := New%sService(%sRepo)
	%sHdlr := New%sHandler(%sSvc)

	%sGroup := api.Group("/%s")
	{
		%sGroup.GET("", %sHdlr.List%s)
		%sGroup.GET("/:id", %sHdlr.Get%s)
		%sGroup.POST("", %sHdlr.Create%s)
		%sGroup.PUT("/:id", %sHdlr.Update%s)
		%sGroup.DELETE("/:id", %sHdlr.Delete%s)
	}
`, t.Name,
			lname, t.Alias,
			lname, t.Alias, lname,
			lname, t.Alias, lname,
			t.Name, t.Name,
			t.Name, lname, t.Alias,
			t.Name, lname, t.Alias,
			t.Name, lname, t.Alias,
			t.Name, lname, t.Alias,
			t.Name, lname, t.Alias))
	}

	b.WriteString("}\n")

	return writeGoFile(pkgDir, "router.go", b.String())
}

// --- helpers ---

func writeGoFile(dir, filename, content string) error {
	path := filepath.Join(dir, filename)
	// Format Go source
	formatted := strings.ReplaceAll(content, "%%", "%") // fix double-% from fmt.Sprintf
	if err := os.WriteFile(path, []byte(formatted), 0644); err != nil {
		return fmt.Errorf("write %s: %w", filename, err)
	}
	fmt.Printf("    • %s\n", filename)
	return nil
}

func toPascal(s string) string {
	if s == "" {
		return s
	}
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	result := strings.Join(parts, "")
	if len(result) > 0 {
		result = strings.ToUpper(result[:1]) + result[1:]
	}
	return result
}

func firstLower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func hasTimeFields(tables []schema.Table) bool {
	for _, t := range tables {
		for _, c := range t.Columns {
			if c.GoType == "time.Time" || c.GoType == "*time.Time" {
				return true
			}
		}
	}
	return false
}
